# Generated by Django 6.1.1 on 2026-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celulares',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
